name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Asegurar archivos correctos en la subcarpeta
        run: |
          if [ ! -d "public" ]; then
            echo "Error: La carpeta 'public' no existe."
            exit 1
          fi
          echo "Archivos en public/:"
          ls -la public/

      - name: Subir artefactos de la carpeta 'public'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public' # Asegura que se despliega el contenido dentro de 'public/'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Activar GitHub Pages si no está activado
      - name: Activar GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r public/* .
          git add .
          git commit -m "Deploy static site to GitHub Pages"
          git push origin gh-pages --force
